spring:
  profiles:
    active: dev   # default profile when you run locally
  jpa:
    hibernate:
      ddl-auto: none   # schema already exists in database.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect	
jwt:
  secret: "EFSt9OcC8XuLjnroV0/0Eltkyc4mZORna4VAV49nm8I="
  expiration: 3600000  # 1 hour in milliseconds
  log-tokens: false