spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dental_lab_app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: springboot_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

# Enable debug logging for development profile
logging:
  level:
    root: DEBUG
    com.dentallab: DEBUG
jwt:
  log-tokens: true